Indian E-Commerce Sales Analytics Dataset

Customers.csv contains customer demographic and registration information.
Products.csv contains products information.
Sales.csv contains transactional sales record.

Database relationships:

customers.csv (customer_id) --> sales.csv (customer_id) and (product_id) --> products.csv (product_id)

What are database relationships?
A database relationship is a connection between two or more tables in a database.

- One-to-one (1:1) one record in one table is linkes to a single record in another table.
- One-to-many (1:M) a single record in one table can be related to multiple records in another table.
- Many-to-many (M:M) records in one table can be related to multiple records in another table.

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
from kagglehub import KaggleDatasetAdapter


#A simple Python library for easily displaying tabular data in a visually appealing ASCII table format.
import prettytable
prettytable.DEFAULT = 'DEFAULT'

from IPython.display import clear_output

/kaggle/input/datasets/jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset/products.csv
/kaggle/input/datasets/jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset/sales.csv
/kaggle/input/datasets/jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset/customers.csv

In [2]:
!pip install ipython-sql
%load_ext sql

!pip install pandasql
import pandasql
# sqldf is a wrapper to run SQL queries on Pandas data frame objects
from pandasql import sqldf

clear_output()

In [3]:
# Load the dataset
customers = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset",
    path = "customers.csv"
)

print("First records:") 
customers.head(3)

First records:

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1977-01-13,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1952-01-20,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,26-35,1994-01-09,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00

In [4]:
# Load the dataset
sales = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset",
    path = "sales.csv"
)

print("First records:") 
sales.head(3)

First records:

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45

In [5]:
# Load the dataset
products = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "jatinkhandelwal112/indian-e-commerce-sales-analytics-dataset",
    path = "products.csv"
)

print("First records:") 
products.head(3)

First records:

,Product_ID,Product_Name,Category,Brand,Original_Price,Discount_Percent,Discount_Amount,Selling_Price,Stock_Quantity,Weight_kg,Avg_Rating,Total_Reviews
0,PROD000001,Samsung Mobile V5,Electronics,Samsung,130561.34,23,30029.11,100532.23,159,2.63,4.49,102
1,PROD000002,HP Laptop V5,Electronics,HP,36494.92,34,12408.27,24086.65,54,4.19,4.32,107
2,PROD000003,boAt Headphones V2,Electronics,boAt,106587.94,42,44766.93,61821.01,638,1.48,4.31,99

https://medium.com/databites/using-sql-with-pandas-dataframes-6dde7fedf483

In [6]:
# sqldf accepts 2 parameters: a SQL query string, and a set of environment variables (locals() or globals()
#) which is optional and can be omitted

pysqldf = lambda q: sqldf(q, globals())

#Any pandas data frames will be automatically detected by pandasql
#We can query any pandas DataFrame using SQL in the same way as we extract data from any table using SQL.

In [7]:
# the SELECT statement is used to retrieve data from a database
# we cna choose specific columns or all columns

# the WHERE is used to filter records based on conditions

pysqldf("SELECT Customer_ID, Customer_Name FROM customers WHERE Customer_ID IS NOT NULL")

        Customer_ID  Customer_Name
0      CUST00000001  Akash Agarwal
1      CUST00000002  Farhan Rahman
2      CUST00000003   Suresh Kumar
3      CUST00000004  Aditya Pandey
4      CUST00000005      Hina Khan
...             ...            ...
39995  CUST00039996    Swati Joshi
39996  CUST00039997   Nikhil Patel
39997  CUST00039998    Akash Yadav
39998  CUST00039999  Salman Ansari
39999  CUST00040000    Ahmed Ahmed

[40000 rows x 2 columns]

In [8]:
pysqldf("SELECT Customer_ID, Customer_Name FROM customers WHERE Age >= 70")

      Customer_ID   Customer_Name
0    CUST00000002   Farhan Rahman
1    CUST00000088  Aamir Siddiqui
2    CUST00000167   Gaurav Mishra
3    CUST00000199     Akash Yadav
4    CUST00000308      Riya Singh
..            ...             ...
462  CUST00039650      Nida Mirza
463  CUST00039685   Rashid Pathan
464  CUST00039825     Aliya Mirza
465  CUST00039850    Aisha Pathan
466  CUST00039974    Gaurav Gupta

[467 rows x 2 columns]

In [9]:
# AND, OR, NOT operators allow to combine multiple conditions in the WHERE clause
pysqldf("SELECT Customer_ID, Customer_Name, Age FROM customers WHERE Age > 70 AND Gender = 'male'")

      Customer_ID   Customer_Name  Age
0    CUST00000002   Farhan Rahman   73
1    CUST00000088  Aamir Siddiqui   73
2    CUST00000167   Gaurav Mishra   73
3    CUST00000199     Akash Yadav   71
4    CUST00000499    Gaurav Mehta   73
..            ...             ...  ...
195  CUST00039034       Zain Khan   73
196  CUST00039153     Hassan Khan   73
197  CUST00039338    Vikas Sharma   72
198  CUST00039372    Farhan Malik   71
199  CUST00039685   Rashid Pathan   75

[200 rows x 3 columns]

In [10]:
# The BETWEEN operator selects values within a range. It is inclusive of the boundary values

pysqldf("SELECT Customer_ID, Customer_Name, Age FROM customers WHERE Age BETWEEN 75 AND 99 ")

     Customer_ID  Customer_Name  Age
0   CUST00000578   Swati Sharma   75
1   CUST00001860     Zara Malik   75
2   CUST00002034    Akash Mehta   75
3   CUST00003648   Suresh Singh   75
4   CUST00003661    Priya Gupta   75
..           ...            ...  ...
68  CUST00038527     Nisha Shah   75
69  CUST00038819    Swati Verma   75
70  CUST00039460  Hina Siddiqui   75
71  CUST00039650     Nida Mirza   75
72  CUST00039685  Rashid Pathan   75

[73 rows x 3 columns]

In [11]:
# The IN operator allows to specify multiple value sin a WHERE clause
pysqldf("""SELECT Customer_ID, Customer_Name, Age, Customer_Tier FROM customers WHERE Customer_Tier IN ('Gold', 'Platinum') 
AND Age > 73""")

     Customer_ID    Customer_Name  Age Customer_Tier
0   CUST00000477  Ananya Kulkarni   74          Gold
1   CUST00000578     Swati Sharma   75      Platinum
2   CUST00001108      Arjun Yadav   74      Platinum
3   CUST00002034      Akash Mehta   75          Gold
4   CUST00002556      Suresh Iyer   74      Platinum
..           ...              ...  ...           ...
88  CUST00035909     Nisha Tiwari   75          Gold
89  CUST00036220       Aarav Shah   75          Gold
90  CUST00038988     Nisha Pandey   74      Platinum
91  CUST00039460    Hina Siddiqui   75      Platinum
92  CUST00039650       Nida Mirza   75      Platinum

[93 rows x 4 columns]

To use directly sql commands we need to create a database, not a dataframe pandas.

In [30]:
import sqlite3

# To interact with an SQLite database, we first need to establish a connection to 
# it using the connect() method

import sqlite3

# conn is the connection to the database object (database.db)
conn = sqlite3.connect("database.db")

customers.to_sql("customers", conn, index=False, if_exists="replace")
products.to_sql("products", conn, index=False, if_exists="replace")
sales.to_sql("sales", conn, index=False, if_exists="replace")

conn.close()

%sql sqlite:///database.db

In [31]:
%%sql
SELECT Customer_ID, Customer_Name, Age, Customer_Tier FROM customers 
WHERE Customer_Tier IN ('Gold', 'Platinum')
AND Age > 74

 * sqlite:///database.db
Done.

[('CUST00000578', 'Swati Sharma', 75, 'Platinum'),
 ('CUST00002034', 'Akash Mehta', 75, 'Gold'),
 ('CUST00003661', 'Priya Gupta', 75, 'Platinum'),
 ('CUST00003681', 'Neha Verma', 75, 'Platinum'),
 ('CUST00004326', 'Shreya Reddy', 75, 'Gold'),
 ('CUST00004856', 'Kavya Patel', 75, 'Platinum'),
 ('CUST00004858', 'Simran Iyer', 75, 'Gold'),
 ('CUST00006890', 'Neha Singh', 75, 'Gold'),
 ('CUST00007416', 'Kuldeep Singh', 75, 'Gold'),
 ('CUST00007802', 'Aditya Iyer', 75, 'Platinum'),
 ('CUST00008077', 'Amina Ahmed', 75, 'Gold'),
 ('CUST00008318', 'Akash Patel', 75, 'Platinum'),
 ('CUST00008873', 'Priya Pandey', 75, 'Gold'),
 ('CUST00010323', 'Gaurav Kumar', 75, 'Platinum'),
 ('CUST00011080', 'Suresh Joshi', 75, 'Platinum'),
 ('CUST00012307', 'Preeti Pandey', 75, 'Gold'),
 ('CUST00014173', 'Ali Malik', 75, 'Platinum'),
 ('CUST00014371', 'Jasleen Singh', 75, 'Gold'),
 ('CUST00014961', 'Nikhil Iyer', 75, 'Platinum'),
 ('CUST00016303', 'Aadhya Sharma', 75, 'Gold'),
 ('CUST00017137', 'Sana Khan', 75, 'Gold'),
 ('CUST00019500', 'Rahul Kulkarni', 75, 'Platinum'),
 ('CUST00019731', 'Ahmed Rahman', 75, 'Gold'),
 ('CUST00020599', 'Harsh Tiwari', 75, 'Gold'),
 ('CUST00021689', 'Karan Sharma', 75, 'Gold'),
 ('CUST00024078', 'Arjun Pandey', 75, 'Gold'),
 ('CUST00024366', 'Abhishek Kumar', 75, 'Gold'),
 ('CUST00025307', 'Raj Sharma', 75, 'Platinum'),
 ('CUST00026870', 'Arjun Kumar', 75, 'Gold'),
 ('CUST00026912', 'Anjali Joshi', 75, 'Gold'),
 ('CUST00028077', 'Divya Mishra', 75, 'Gold'),
 ('CUST00028762', 'Shreya Singh', 75, 'Gold'),
 ('CUST00028952', 'Vishal Yadav', 75, 'Gold'),
 ('CUST00029255', 'Arif Mirza', 75, 'Platinum'),
 ('CUST00029501', 'Amit Kulkarni', 75, 'Gold'),
 ('CUST00029652', 'Neha Patel', 75, 'Gold'),
 ('CUST00029869', 'Suresh Gupta', 75, 'Gold'),
 ('CUST00030101', 'Abhishek Kulkarni', 75, 'Platinum'),
 ('CUST00031352', 'Aarav Mishra', 75, 'Platinum'),
 ('CUST00032032', 'Harsh Gupta', 75, 'Platinum'),
 ('CUST00032056', 'Simran Yadav', 75, 'Platinum'),
 ('CUST00032438', 'Abhishek Nair', 75, 'Platinum'),
 ('CUST00032760', 'Swati Mishra', 75, 'Platinum'),
 ('CUST00034304', 'Vishal Mehta', 75, 'Platinum'),
 ('CUST00034878', 'Divya Kulkarni', 75, 'Platinum'),
 ('CUST00035909', 'Nisha Tiwari', 75, 'Gold'),
 ('CUST00036220', 'Aarav Shah', 75, 'Gold'),
 ('CUST00039460', 'Hina Siddiqui', 75, 'Platinum'),
 ('CUST00039650', 'Nida Mirza', 75, 'Platinum')]

In [40]:
%%sql
-- The LIKE operator searches for a specified pattern
-- % = any number of characters
-- _ = a single character
-- Select customers whose name contains "ali"

SELECT Customer_ID, Customer_Name, Age
FROM customers
WHERE Customer_Name LIKE '%alid%'
AND Age in (45,60)

 * sqlite:///database.db
Done.

[('CUST00004234', 'Khalid Sheikh', 45),
 ('CUST00004707', 'Khalid Khan', 45),
 ('CUST00009550', 'Khalid Ali', 60),
 ('CUST00021986', 'Khalid Khan', 45),
 ('CUST00036265', 'Khalid Rahman', 45)]

In [56]:
%%sql
-- The ORDER BY clause is used to sort the result set in ascending or descending order
-- by default, it sorts in ascending order
-- ASC: ascending, DESC descending

SELECT Customer_Name, Age FROM customers WHERE Age in (19,22) AND
Customer_Name LIKE '%priya%'
ORDER BY Age DESC

 * sqlite:///database.db
Done.

[('Priya Reddy', 22),
 ('Priya Yadav', 22),
 ('Priya Mehta', 22),
 ('Priya Nair', 22),
 ('Priya Iyer', 22),
 ('Priya Agarwal', 22),
 ('Priya Yadav', 22),
 ('Priya Mehta', 22),
 ('Priya Mishra', 22),
 ('Priya Agarwal', 22),
 ('Priya Joshi', 22),
 ('Priya Joshi', 22),
 ('Priya Iyer', 22),
 ('Priya Nair', 22),
 ('Priya Shah', 22),
 ('Priya Mishra', 22),
 ('Priya Reddy', 22),
 ('Priya Shah', 22),
 ('Priya Kumar', 22),
 ('Priya Patel', 22),
 ('Priya Mehta', 22),
 ('Priya Tiwari', 22),
 ('Priya Singh', 22),
 ('Priya Agarwal', 22),
 ('Priya Shah', 22),
 ('Priya Mehta', 22),
 ('Priya Patel', 22),
 ('Priya Joshi', 22),
 ('Priya Sharma', 19),
 ('Priya Joshi', 19),
 ('Priya Nair', 19),
 ('Priya Yadav', 19),
 ('Priya Sharma', 19),
 ('Priya Sharma', 19),
 ('Priya Shah', 19),
 ('Priya Singh', 19),
 ('Priya Kumar', 19),
 ('Priya Pandey', 19),
 ('Priya Sharma', 19),
 ('Priya Gupta', 19),
 ('Priya Nair', 19),
 ('Priya Shah', 19),
 ('Priya Sharma', 19),
 ('Priya Pandey', 19),
 ('Priya Kulkarni', 19),
 ('Priya Agarwal', 19),
 ('Priya Tiwari', 19),
 ('Priya Kulkarni', 19),
 ('Priya Agarwal', 19),
 ('Priya Kumar', 19),
 ('Priya Kulkarni', 19),
 ('Priya Kulkarni', 19),
 ('Priya Reddy', 19),
 ('Priya Sharma', 19),
 ('Priya Kulkarni', 19),
 ('Priya Kulkarni', 19),
 ('Priya Pandey', 19),
 ('Priya Mishra', 19),
 ('Priya Gupta', 19),
 ('Priya Shah', 19),
 ('Priya Kulkarni', 19),
 ('Priya Joshi', 19),
 ('Priya Tiwari', 19),
 ('Priya Singh', 19)]

## Aggregate data

In [60]:
sales.head(2)

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25

In [59]:
products.head(2)

,Product_ID,Product_Name,Category,Brand,Original_Price,Discount_Percent,Discount_Amount,Selling_Price,Stock_Quantity,Weight_kg,Avg_Rating,Total_Reviews
0,PROD000001,Samsung Mobile V5,Electronics,Samsung,130561.34,23,30029.11,100532.23,159,2.63,4.49,102
1,PROD000002,HP Laptop V5,Electronics,HP,36494.92,34,12408.27,24086.65,54,4.19,4.32,107

In [61]:
customers.head(2)

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1977-01-13,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1952-01-20,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24

In [63]:
%%sql
--perform calculations on a set of values
-- SUM returns the total sum of a numeric columns, AVG the average
-- COUNT returns the number of rows of non-null values

SELECT SUM(Selling_Price), AVG(Selling_Price), COUNT(Selling_Price) 
FROM products WHERE Category = 'Electronics'

 * sqlite:///database.db
Done.

[(15173384.709999999, 52322.01624137931, 290)]

In [73]:
%%sql
SELECT SUM(Selling_Price) AS total_price FROM products;

 * sqlite:///database.db
Done.

[(26360678.14,)]

In [77]:
%%sql
SELECT AVG(Selling_Price) AS avg_price FROM products

 * sqlite:///database.db
Done.

[(13180.33907,)]

In [83]:
%%sql

-- the GROUP BY statement is used to group rows that have the same values in specific columns

SELECT Category, SUM(Selling_Price) AS 'tot selling price'
FROM products
GROUP BY Category

 * sqlite:///database.db
Done.

[('Beauty', 527855.1900000001),
 ('Books', 210156.17),
 ('Electronics', 15173384.709999999),
 ('Fashion', 1544810.32),
 ('Grocery', 287568.63),
 ('Home', 4892650.68),
 ('Sports', 3724252.44)]

In [87]:
result = pysqldf(""" SELECT Category, SUM(Selling_Price) AS 'tot selling price'
FROM products
GROUP BY Category """)

result.head(3)

      Category  tot selling price
0       Beauty          527855.19
1        Books          210156.17
2  Electronics        15173384.71

In [88]:
%%sql

-- the HAVING clause is used to filter records after grouping,
-- similar to WHERE; but HAVING operates on aggregated data

SELECT Category, SUM(Selling_Price) AS 'tot selling price'
FROM products
GROUP BY Category
HAVING Category in ('Beauty', 'Books')

 * sqlite:///database.db
Done.

[('Beauty', 527855.1900000001), ('Books', 210156.17)]

In [94]:
%%sql

SELECT Category, SUM(Selling_Price) AS tot_selling_price
FROM products
GROUP BY Category
HAVING tot_selling_price < 220000

 * sqlite:///database.db
Done.

[('Books', 210156.17)]

In [98]:
%%sql

-- the DISTINCT keyword is used to return only unique values

SELECT DISTINCT Category from products

 * sqlite:///database.db
Done.

[('Electronics',),
 ('Fashion',),
 ('Home',),
 ('Beauty',),
 ('Sports',),
 ('Books',),
 ('Grocery',)]

## SQL ARITHMETIC

In [108]:
%%sql

-- ex to subtract 10% of sale

SELECT Product_Name, Selling_Price, (Selling_Price*0.1) AS Sale, Selling_Price-(Selling_Price*0.1) AS selling_price_sale 
FROM products
WHERE Sale > 12000

 * sqlite:///database.db
Done.

[('Apple iPhone V9', 136973.33, 13697.332999999999, 123275.99699999999),
 ('Samsung Mobile V4', 127597.19, 12759.719000000001, 114837.471),
 ('Apple iPhone V3', 123191.16, 12319.116000000002, 110872.044)]

In [112]:
%%sql
-- There are also CEIL, FLOOR, ABS, ROUND commands

SELECT Product_Name, Selling_Price, ROUND(Selling_Price*0.1, 2) AS Sale, ROUND(Selling_Price-(Selling_Price*0.1),2) 
AS selling_price_sale 
FROM products
WHERE Sale > 12000

 * sqlite:///database.db
Done.

[('Apple iPhone V9', 136973.33, 13697.33, 123276.0),
 ('Samsung Mobile V4', 127597.19, 12759.72, 114837.47),
 ('Apple iPhone V3', 123191.16, 12319.12, 110872.04)]

In [ ]:
# Division is done with / 
# Multiplication with *

## NULL values

In [114]:
%%sql

-- there are also functions like IS NULL; IS NOT NULL, COALESCE() to handle null values

SELECT * FROM products WHERE Selling_Price IS NULL

 * sqlite:///database.db
Done.

[]

In [1]:
%%sql

-- returns 0 if the price is NULL

SELECT COALESCE(Selling_Price, 0) FROM products
WHERE Selling_Price > 500000

UsageError: Cell magic `%%sql` not found.